iron/iron

src/response/mod.rs

[New array syntax](https://github.com/rust-lang/rust/pull/20387).

(fix) Update to use new array syntax.

---

src/modifiers.rs

This makes redirects work again.

(fix) Fixed bug in redirect code

---

examples/error.rs
src/middleware.rs
src/request/mod.rs
src/request/url.rs
src/response.rs

* Replacing `fmt::Show` with `fmt::Debug`, `fmt::String` with `fmt::Display`.
* Replacing `str::StrExt::slice_from` with `&s[start..]` notation.

(fix) Update to the latest rustc (4874ca36f 2015-01-23)

---

examples/redirect.rs

Also move url parsing out of the closure to demonstrate
moving into closure handlers.

(fix) Use the correct status code in the redirect example.

---

.gitignore
src/iron.rs
src/middleware/test.rs
src/modifiers.rs
src/request/mod.rs
src/response.rs

- Fixed imports and io:: references
- Fixed deprecated Writer::write calls to use Writer::write_all

Fixes around std::io being renamed to std::old_io

---

examples/404.rs
examples/around.rs
examples/error.rs
examples/redirect.rs

Removed the println! that are no longer called and moved a the more useful one within examples/around.rs above the listen calls.

(cleanup) Removed the println! that are no longer called

---

README.md
examples/404.rs
examples/around.rs
examples/error.rs
examples/hello.rs
examples/redirect.rs
examples/time.rs
src/iron.rs
src/lib.rs
src/request/mod.rs

This adds a security property to iron::Iron, defaulting to 'Insecure'.
Setting it to 'Secure' and specifying certificate and key paths allows
the server to use HTTPS.
Also fix a FIXME in Request::from_http now that HTTPS connections
are possible.

(feat) Add ability to serve over HTTPS.

---

examples/404.rs
examples/hello.rs
examples/redirect.rs
src/iron.rs
src/lib.rs
src/middleware/test.rs
src/modifiers.rs
src/request/mod.rs
src/response.rs

These changes depend on hyperium/hyper#354

Move to new io/fs/path API and adjust to Hyper changes

---

src/lib.rs

Removing `#![feature(fs)]` makes iron finally compile on my machine.

Remove the fs feature gate.

---

Cargo.toml
src/lib.rs
src/modifiers.rs

Taken from iron/static#14. This pull should not be accepted as-is. `mime_types::Types::new()` loads a media type lookup table from a JSON file, and that probably shouldn't be done every request for obvious performance reasons. Any ideas as to where we can store this object? In `Iron` somehow? Maybe a static (singleton generating) method?

(feat) Set content type automatically for based on file extension

---

src/middleware/test.rs
src/modifiers.rs
src/request/mod.rs

The request body type now has two lifetime parameters.
Fixes #313

(fix) Add a second request lifetime for hyper changes.

---

src/lib.rs
src/modifiers.rs

This involves a little bit of shenanigans with File modifiers,
which no longer set the content type. Instead, you must use a Path
or PathBuf modifier if you want the content type to be set.
Fixes #318

(feat) Build on only stable rust.

---

examples/error.rs

rustc : rustc 1.0.0-nightly (2e3b0c051 2015-04-01) (built 2015-04-01)
I have worked in
* [feature(core)] is removed because it is not necessary anymore.

[feature(core)] is not necessary on the latest rustc.

---

src/iron.rs

This is a simple documentation addition adding a few lines talking about the guard returned by a `thread::scoped` thread.

(doc) This addresses issue 319 to describe the threading model used by the Hyper library.

---

README.md

It drives me a little nuts seeing badges with slight differences in style on a project's README.  
This PR uses [shields.io](http://shields.io) to style the Build and Crates.io badges more consistently.

(doc) use shields.io badges for consistency

---

src/lib.rs

Exported as iron::status::StatusClass;
Needed to support iron/logger#57

(fix) Reexport hyper::status::StatusClass

---

src/middleware/mod.rs

Hi, I was working on live-reload feature on my [handlebars-iron](https://github.com/sunng87/handlebars-iron/tree/feature/notify) middleware. In order to watch the file system and reload template engine, I spawned a dedicated thread waiting for fs events. The middleware is shared in main thread and watcher thread. So I made it wrapped by Arc.
I hope iron could accept Arc wrapped value as `BeforeMiddleware` and `AfterMiddleware`. Otherwise, it seems difficult to set an Arc into Chain.
The code with modified iron is here:
https://github.com/sunng87/handlebars-iron/blob/feature/notify/examples/watch_server.rs#L50
If there is a better solution for this scenario, please kindly let me know. :-)

(feat) allow Arc wrapped value as middleware

---

examples/error.rs

Clarify the error example by using a status::BadRequest in the error
case, and status::Ok in the normal case (which is never triggered).

Distinguish error by using status::BadRequest

---

README.md
src/lib.rs

Fixed 'automatic' typo in docs

---

src/lib.rs

Previously, the 'for ' part blended into the description on the main page.
By putting it on a new line, the index is better formatted.

Fix prelude doc formatting.

---

src/modifiers.rs
src/response.rs

A `Read`er is not the best abstraction for the response body - it has to
be copied to the output `Write`r through an extra intermediary buffer
and complicates the implementation for users that want to compute the
response on the fly.
This design is modeled after Java JAX-RS's StreamingOutput class. The
`write_body` method takes the Hyper `Response` object concretely instead
of a generic `Write`r to allow for future optimizations with Hyper, for
example, allowing the underlying file descriptor to be retrieved for use
with `sendfile` on Linux.
This is a [breaking-change]

Switch response abstraction from `Read` to `WriteBody`.

---

src/lib.rs

```
warning: unused variable: `req`, #[warn(unused_variables)] on by default
Iron::new(|req: &mut Request| {
```

(doc) Remove warning

---

src/middleware/mod.rs

This commit modifies `Chain.link()`, `Chain.link_before()`, `Chain.link_after()`, and `Chain.around()` to return a reference to the current `Chain`. This allows the, ahem, "chaining" of calls to these functions, which is slightly more ergonomic than the way things are now.
All tests pass locally with these changes, but I'm not sure how to best add tests to check this specific change.
This addresses issue #353.

(refactor) Added return to link functions on Chain

---

examples/error_recovery.rs
examples/simple_routing.rs

Hi,
I've started using Iron for personal projects and have written some example code while learning to use the framework. I added two examples:
- `error_recovery.rs` illustrates how to recover from an error in a middleware piece. I tried that to see how the request switches from the normal flow to the error flow.
- `simple_routing.rs` illustrates how to select a specific handler depending on the request. (I learned about the [routing middleware](https://github.com/iron/router) afterwards, which is obviously a better solution, but I think the example can be useful for learning.)
I hope this can help people discovering the framework.

Adding examples

---

src/response.rs

The `Response` body no longer implements `Read` since 6c737893ac07846070ff896e07a3ccfffa246fd3

Remove outdated response body documentation

---

src/middleware/mod.rs

This is a small change that just renames `Chain.around()` to `Chain.link_around()`, for consistency with the other linking functions.

(refactor) Rename around() to link_around()

---

src/lib.rs

First "its" is definitely possessive and second one should go due to the first one already expressing possessiveness.

Fix some grammar

---

src/iron.rs

To make it consistent with what the [doc](https://github.com/iwinux/iron/blob/165daff62dfc6c0050f6706633c7a3f08b7b8dfe/src/iron.rs#L105) says:
> Defaults to a threadpool of size `2 * num_cpus`.

Update doc about default number of threads

---

src/modifiers.rs
src/response.rs

A non-Send WriteBody is not very useful, since Response requires a Send
WriteBody. While this is slightly less general since WriteBody can no
longer be used fully in other contexts it makes for simpler and more
likely-to-be-correct generic uses of it.
Technically a breaking change, but I can hardly imagine there is any
actual breakage as a result of this change

(feat) Make WriteBody require Send, shortening and clarifying bounds.

---

src/modifiers.rs
src/response.rs

This allows to easily set a `Read`er as response body without dealing with `as Box<WriteBody>` shenanigans.
```rust
let reader = io::empty();
Response::with(BodyReader(reader));
```
I'm not sure if we actually want to implement it this way.
The pros are that we can avoid annoying type wrestling and double-boxing.
The cons are that we need to introduce intermediate types like `BodyReader`.

(feat) Add BodyReader wrapper

---

examples/simple_routing.rs

The two "hello" routes by default will be set to `status::NotFound`, but the routes return data like a typical request so `status::Ok` seems more appropriate.

(fix) Set status::Ok on expected routes in simple_routing example.

---

Cargo.toml

One particular annoyance is that hyper 0.7 pulls in a version of mime that unnecessarily pulls in serde as a dependency.

Update hyper to 0.8

---

src/modifiers.rs

RedirectRaw is necessary to allow redirection to urls which don't have special schemes (and therefore are incompatible with Redirect) such as oob:// and steam://
This patch allows construction of RedirectRaw by making the inner field public.

make RedirectRaw's field public to allow construction

---

Cargo.toml
examples/simple_routing.rs
src/request/url.rs

Rather than doing so many conversions back and forth.
This builds on #452 and contains 3 commits more than that PR.
Commits eea2bbf and bef95ae are fairly straightforward. eea2bbf gets rid of the extra `rust-url` parse call needed since `rust-url` 1.0 to get back to a `rust-url` `Url`. bef95ae uses `rust-url`'s display implementation on the stored `rust-url` `Url` for the `iron` `Url`'s display trait-- all the tests still pass.
3a9b322 may be a step too far-- I'm happy to remove it if so. It changes the public API of `iron` `Url` to have methods instead of the struct fields, and those methods mostly just delegate to the `rust-url` `Url`. I'm not sure if this is what you had in mind or not!

Hold onto rust-url Url in iron Url

---

src/response.rs

Fixes #473 
Hyper prints the canonical reason for the status now.

Response Format

---

Cargo.toml

In the process of updating the dependencies of another far upstream package that eventually includes iron, I noticed that `num_cpus` had finally stabilized and made a 1.0 release. There were no code changes in the `1.0` release from `0.2.13` (https://github.com/seanmonstar/num_cpus/commit/7aab1fbc30b9bf39e74b0624dc037af694ce4da3)
The tests for iron pass on my machine, with one ignored test??: `test itry!_0 ... ignored`.

(refactor) bump version of `num_cpus` to 1.0

---

src/request/url.rs

When I want to read data from the underlying `url::Url` (either because
it offers a richer API than Iron's URL for my usecases, or because I can
pass it directly into another API), I currently have two choices:
- `let url = request.url.into_generic_url().clone()`. This unnecessarily
copies data.
- `let url = request.url.into_generic_url()`, which moves `request.url`,
and do `request.url = iron::Url::from_generic_url(url)` when I'm done,
to move the generic URL back into the request. This is unnecessarily
verbose.
Both options are undesirable. Therefore `generic_url`.
I also have similar usecase for `generic_url_mut`. I have a middleware
that modifies a part of the request URL. Currently I'd have to do
similar tricks to do that.

Improve conversion of iron::Url from/to url::Url

---

examples/https.rs

Needs to use cfg flags because of the 'ssl' feature not being default.
If we don't do this then `cargo test` will fail.
@untitaker can you review and merge if it's good?

(example) Add HTTPS example.

---

src/request/mod.rs

This assumes the local_addr is good enough to generate a URL against, but that's probably not going to be true often (ever?). I'm open to better suggestions.
```bash
$ curl --dump-header - -0 -H 'Host:' localhost:3000
HTTP/1.0 200 OK
Date: Sat, 01 Oct 2016 07:52:37 GMT
Content-Type: text/plain
Content-Length: 12
Hello world!%
```
This is a reopened version of #362 and fixes #327.

(fix) Don't reject HTTP <= 1.0 requests without a Host header.

---

Cargo.toml
examples/content_type.rs

Make content type example more idiomatic and thereby safe. Not sure if `ContentType::json().0` looks nice, but definitely works without `.unwrap()` since the JSON content type is built-in.
Old example was copied to `examples/content_type_custom.rs` and another alternative added in a comment.

(doc) Make content type example more idiomatic, add another example for full customization

---

src/request/mod.rs

Most of the time, when the Host header and local address don't match, it's because we're behind a reverse proxy. In this case, using the local port (which is likely an internal port such as "8080") doesn't make sense.

Don't mix up local address and Host header

---

README.md

According to the output here: https://github.com/iron/iron/wiki/How-to-Benchmark-hello.rs-Example
> Requests/sec:  72479.41

Correct requests/sec avg in README

---

.travis.yml
Cargo.toml
examples/hello_custom_config.rs
examples/https.rs
src/iron.rs

The previous support for SSL was not great - you were locked into
OpenSSL and had no ability to configure it the way you wanted. Hyper is
going to be cutting a release soon that completely removes the built-in
OpenSSL and Secure Transport functionalty in favor of external crates.
While we're at it, also allow a `NetworkListener` to be manually
created, and refactor the configuration a bit to avoid combinatoric
blowup in methods.
Closes #483
Closes #447
Closes #424
r? @untitaker 
It probably makes sense to land this along with the hyper upgrade. @seanmonstar, do you have an idea on when that'll be roughly?
The optional OpenSSL dependency hopefully won't cause problems, but it seemed important to keep the https example around.

Refactor server startup APIs and Https support

---

src/error.rs
src/iron.rs
src/lib.rs
src/middleware/mod.rs
src/request/mod.rs
src/request/url.rs
src/response.rs

- Markdown in docstrings.
- Remove some needless clones.
- Get rid of pattern matching references to references.

Cleanup some clippy lints.

---

src/request/url.rs

This is to allow the use of the FromStr trait to create a Url directly from string, and for example use:
let u = "https://en.wikipedia.org/wiki/Rust_(programming_language)".parse().unwrap();
let redirect = iron::modifiers::Redirect(u);
instead of:
let u = iron::Url::parse("https://en.wikipedia.org/wiki/Rust_(programming_language)").unwrap();
let redirect = iron::modifiers::Redirect(u);

Adding a from_str method

---

src/request/url.rs

Before I saw your merge (thanks!) I thought one simple positive and one simple negative test would be good for when that particular piece of code is changed. No need to do anything more complicated given that there are already tests by parse() itself.

adding two simple tests for from_str

---

examples/echo.rs

Shows how to read request body and echo it back in a response, including
error handling.

(doc) Add echo example

---

src/middleware/mod.rs

Just something I noticed while reading through the docs.

(doc) Fix typo in `Handler` description

---

Cargo.toml
src/lib.rs
src/modifiers.rs

A couple of reasons:
* conduit-mime-types does not look actively maintained, its last commit was 2 years ago
* It depends on the deprecated rustc-serialize for parsing JSON at runtime
* mime_guess uses a compile-time hash map, which means we also don't need lazy_static anymore either
I split it into two commits: The first one adds tests for the existing functionality. The second one replaces the implementation while keeping the tests.
Here's the result of running [cargo tree](https://github.com/sfackler/cargo-tree) before and after:
```diff
@@ -1,6 +1,4 @@
iron v0.5.1 (file:///Users/rstocker/Projects/rust/iron)
-├── conduit-mime-types v0.7.3
-│   └── rustc-serialize v0.3.24
├── hyper v0.10.10
│   ├── base64 v0.5.2
│   │   └── byteorder v1.0.0
@@ -23,8 +21,14 @@
│       │   │   └── matches …
```

Replace conduit-mime-types dep by mime_guess

---

examples/https.rs

Fix typo in openssl example

---

examples/https.rs

Hello!
When I wanted to generate a ssh key, I got the following error.
```
Invalid password argument "mypass"
Error getting passwords
```
`pass:` may fix this issue.

(doc) fix ssh key generating command error

---

README.md

The last release of iron (0.6.0) took months to do and required a lot of pushing
from an outsider (me), see #551. Given that, I think it's fair to say that iron
is unmaintained and at this point I would advise new people not to use it.
If any of that changes, we can remove the notice again.
CC @untitaker

README: Add note about maintenance status of iron

---

src/iron.rs

The reason why the Iron - router does not work is that it is the protocol scheme http. 
When initializing the HTTPS listener, we fixed it by changing the call to Protocol::http() to the call of Protocol::https().
best regards

Fixed an issue where iron-routers does not work when using HTTPS listener.

---

README.md

As Iron is being maintained again and is about to release a new version using hyper 0.12, this note is removed in order to not discourage people from using iron.
This reverts commit 9e5bccb407b1ec8daef51b0d7494627e5c5fc307.
(This PR can be merged whenever we feel confident about releasing iron 0.7.)

Revert "README: Add note about maintenance status of iron (#576)"

---

src/iron.rs
src/response.rs

This commit resolves #582, where the content-length header of HEAD responses were overwritten as 0. Here my solution was to just pass along the request method to `write_back` and then return Ok if the body is empty and the method is HEAD.
To replicate the original problem and verify my solution, I created an [example project](https://github.com/bplower/iron-verify-issue-582) with a hardcoded response. That response has no body and has a hardcoded content-length of 123. The readme there covers how to run the project, switching between the iron/iron repo and the bplower/iron fork. In short though, running with the latest version of iron gives:
```
curl -s -i --head http://localhost:3000 | grep content-length
content-length: 0
```
and running with the changes in this pull request gives:
``` …
```

(fix) Preserve content-length in HEAD response [Fixes #582]

---

src/request/mod.rs

https://github.com/iron/iron/issues/594

(fix) Use port_part() insead of deprecated port()

---

src/error.rs

This should fix the nightly build (which is currently failing due to the `cause` deprecation warning).

Use source instead of cause in Error trait

---

README.md

This adds a note that the example currently does not work with the `iron` version released on crates.io.

Update README.md with note for the example

---

Cargo.toml

The first commit contains the fix in-of itself, the following two fix the CI builds on newer `rustc`s.
Ref: https://github.com/thecoshman/http/issues/85
Ref: #584

Fix outdated hyper-native-tls in 0.6

---

examples/echo_query.rs
src/request/mod.rs

This PR fixes iron completely ignoring query strings.
I guess the regression was introduced with some changes in the hyper `uri` module that no longer seems to include the query string in the `path` section of the request URL. I did not have time to look into the exact cause yet, though.

Fix query strings

---

logger/README.md

Two links point to the old rust doc urls. This PR updates those to their newer docs.rs urls. Additionally, fixed some grammar here and there.

(doc) fix broken logger link

---

iron/src/modifiers.rs

**Current Behavior**
The comments on `modifiers.rs` point to a deprecated (404) URL of the remote `modifiers.rs` file
https://github.com/iron/iron/issues/618
**New Behavior**
The comments on `modifiers.rs` point the correct URL

(doc) Fixed modifiers remote link

---

iron/src/request/mod.rs
iron/src/request/url.rs
iron/src/response.rs

For some reason query strings were no longer being taken into consideration
and the routes would get no query string value at all if they wanted to.
So this fixes #617 and adds a test to ensure it won't come back.
Several compilation errors related to try! macro were fixed as well.

Put query string into request URL
