- src/iron.rs
- src/request/mod.rs
Closes #245.
Not sure if this is the best approach. The alternative is modifying Hyper so that it includes the local `SocketAddr` in its request struct. You'd probably be a better judge of this @reem, given your involvement with Hyper.
> (fix) Include port in URLs again.

- src/middleware/test.rs
- src/request/mod.rs
This changes the behavior of Iron in a rather crucial way.
Instead of reading the entire body of an incoming Request into a
`Vec<u8>` at the creation time of a Request, the body is now
exposed as a Reader on the Request object and can be read on-demand
or not-at-all depending on its use.
Streaming is critical for uses such as file uploading, where loading
the entire request body into memory unconditionally is... bad.
The body is exposed as a mostly opaque `Body` type which implements
`Reader` and wraps hyper's `HttpReader<&'a mut (Reader + 'a)>`. The http
reader cannot currently be retrieved from a `Body`, but for testing
purposes `Body::new` can be used to construct a `Body` from an `HttpReader`.
Progress on #263
Fixes #265
> (feat) Stream the body of a Request as a Reader

- src/modifiers.rs
(Note: debug builds are blocked by rust-lang/rust#22432)
> Implement Modifier for &Path

- src/lib.rs
> (chore) Purge unsafe from src.

- src/iron.rs
- src/lib.rs
fixes https://github.com/iron/iron/issues/315
> update to work with latest Rust nightly

- src/error.rs
- src/lib.rs
- src/middleware/test.rs
- src/modifiers.rs
- src/request/mod.rs
- src/request/url.rs
> (chore) Remove some unstable features and gates.

- README.md
But may better will be just copy-paste from examples/time.rs....
> (fix) Update example in README.md compatible with version 0.1.18

- src/iron.rs
Eliminates use of the `return` keyword. Clearer `fn bad_request`. Refactored `fn handle` into a single expression.
> (refactor) iron.rs

- src/request/url.rs
See: https://lists.w3.org/Archives/Public/public-whatwg-archive/2015Jun/0028
https://github.com/whatwg/url/commit/d5470b8d02
Closes #309
> Rename "relative scheme" to "special scheme" according to URL spec.

- README.md
> (doc) Typo in readme: milage -> mileage

- src/lib.rs
I had to figure out what all to import to actually get this to work.
No worries if you don't want to take this, but I think showing the full thing is much better in this case.
> Make the hello world a real hello world.

- src/request/url.rs
Adds tests for username and password presence.
> Add more tests for username and password in `Url` module

- src/iron.rs
> Return 500 server error in case of panic

- src/iron.rs
We also bump the default thread pool size to 8 threads per core, to be slightly
more resistant to starvation.
Depends on hyperium/hyper#697
> Re-enable keep-alive by default, allow setting read, write, and keep-alive timeouts.

- src/modifiers.rs
- src/request/mod.rs
- src/request/url.rs
- src/response.rs
> (refactor) clippy run

- src/modifiers.rs
Signed-off-by: Mike Tang <miketang84@outlook.com>
> add a new modifier RedirectRaw .

- src/lib.rs
> (fix) Publicize the Timeouts type to allow setting timeouts.

- src/macros.rs
More usage examples and link to modifiers docs.
> Expand docs on itry!

- src/modifiers.rs
I hope this should make them more accessible to newbies (like me).
> Expand docs on modifiers

- .travis.yml
- Cargo.toml
> Remove ssl as a default feature

- src/request/url.rs
Fixes #442 
I also added a few tests to ensure the conditional is covered correctly.
> Url Display Refactor

- circle.yml
Reference: https://github.com/rust-lang/cargo/issues/2429
Don't merge until CircleCI works!
> Add override of command for CircleCI.

- examples/hello_custom_config.rs
add hello server example with custom config.
> (example) add new example

- Cargo.toml
> Update to Hyper 0.10

- src/response.rs
This originally existed to avoid having to wrap the Hyper Respnose in a
trait object, but since we're doing that now anyway we may as well avoid
the extra indirection
r? @untitaker
> Remove ResponseBody

- src/modifiers.rs
This now shares code with the Modifier impl for Path, which already sets the MIME type.
> Make PathBuf set the MIME type based on the path

- README.md
It's faster, more modern, and written in rust! :D
> Readme: use ripgrep instead of ack

- router/src/router.rs
closes https://github.com/iron/router/issues/148
- update route-recognizer (implicitly)
- add `dyn` to trait objects
> fix nightly build of router crate
